{% set name = "MDAnalysisTests" %}
{% set version = "2.9.0" %}
{% set sha256 = "8e4942ec3aaef5e93aeb39690293764ab9995550135ff1bd0df2f40cb95c0626" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.lower() }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.14a0
    - mdanalysis =={{ version }}
    - pytest >=3.3.0
    - hypothesis

test:
  requires:
    - python {{ python_min }}
  imports:
    - MDAnalysisTests
    - MDAnalysisTests.datafiles

about:
  home: https://github.com/MDAnalysis/mdanalysis
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Tests and test files for MDAnalysis package

extra:
  recipe-maintainers:
    - hmacdope
    - orbeckst
    - richardjgowers
    - kain88-de
    - ialibay
    - RMeli
    - lilyminium
    - fiona-naughton
