{% set name = "MDAnalysisTests" %}
{% set version = "2.6.0" %}
{% set sha256 = "16fdd10e5240b606e8f9210b7cbd9e4be110e6b8d79bb6e72ce6250c4731a817" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9,<=3.11
    - pip
    - setuptools
  run:
    - python >=3.9,<=3.11
    - mdanalysis =={{ version }}
    - pytest >=3.3.0
    - hypothesis

test:
  imports:
    - MDAnalysisTests
    - MDAnalysisTests.datafiles

about:
  home: https://github.com/MDAnalysis/mdanalysis
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Tests and test files for MDAnalysis package

extra:
  recipe-maintainers:
    - orbeckst
    - richardjgowers
    - kain88-de
    - ialibay
