{% set name = "MDAnalysisTests" %}
{% set version = "2.6.1" %}
{% set sha256 = "043f7451f4d9c42ea9e6609a81a6002948e2c74fd268282e0831416789b22e5e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9,<=3.11
    - pip
    - setuptools
  run:
    - python >=3.9,<=3.11
    - mdanalysis =={{ version }}
    - pytest >=3.3.0
    - hypothesis

test:
  imports:
    - MDAnalysisTests
    - MDAnalysisTests.datafiles

about:
  home: https://github.com/MDAnalysis/mdanalysis
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Tests and test files for MDAnalysis package

extra:
  recipe-maintainers:
    - orbeckst
    - richardjgowers
    - kain88-de
    - ialibay
