{% set name = "MDAnalysisTests" %}
{% set version = "0.16.1" %}
{% set sha256 = "b825eaf90414ff4cc145aea2c1ed0bd46e2796bf628714f379ebd980b6151829" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py3k or win]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - mdanalysis =={{ version }}
    - nose ==1.3.7
    - psutil
    - mock

test:
  imports:
    - MDAnalysisTests
    - MDAnalysisTests.datafiles

about:
  home: https://github.com/MDAnalysis/mdanalysis
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Tests and test files for MDAnalysis package'

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
