# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hk8It+6RA2QaNc3xTiYLgDrYzAnrouRiCSxW6MvzN2ORHLCzqYA3mFMSizkiaWFFYtX9iX2fnvh4QofdqMEVGYvrYN8ld2aF/qQRlgXNRoBbRwe/xONUbPrzmkKe2NQXi8zmNr8FLQQp88F5QjYa+LMsdcPUr60qsTbwQ5wB+cjXqukKV1kOIA2jkC0cUu7jLuBLUC+2V0jmq51Thp8hH+KMzIv+OsUID6uzsl+FdpdKLdUNe3WHEfDeZeWhrwIACi6ONFR7AZwvCvU11g45oVfBIAPED9AIwmWe/bAE87qmyd+RXiaMKUyWL5VYKqHG+dA0agvwjqf1WhUR2/gsZQdeYevS/LG7xNGtgd/rlTZr62wJitmdj5S+gerWUz9led9RJdCeSl2Y3RspO2YevG/oPpnsie5Rik9r9SIOBDYPSes0SX/q18QSo5A5byiRCDI8nUblruqc3rbA0PU4nuO7AIG4V8cecOeI9vnegHTGkpDoMOVu9qHKA8+wv22ImViYxltDwysdOxJvSKjepX//cKgzodQqs6hARkL9zl9Y98B3wSItNL+XghPOmCIqURf6VBIZqCHuAA/Ot6B6IvM6JwEh5B63KuxRCr0hp3FMqm6XBsKRb/CUn+OIGj2hagD0aan30XDe+btPz0uoQbhSACu9ORTLXYZ5+1OSZAM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
