# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hkl3+un8BzNHl1oUpbfsz+ZQ2D/91ge8B9reGe+33OlpzgXK3wEs+4oqpY8wez9k1lyh4sss4EVa4BR+q5GGFfOI+AO0OVVmGyepfD8EgVcQfobBuysvim84lPaZ+XiXDtDYUecuTX296EOQDwjAG3IEpAyzCE6ZM/XYrx48arxvZ1FhoAPyyILEeqZ4dI3Iyg9DH15YX3J06wuWP5qYa/VAJzVJo8kVHayba0Ob4XnTL47z/WlyE19pm2lycLSIVEUi+bMNeMkVUD7sj9+Qb7bK5G9w4gwYcM8fRIJukfLFNsD03LMBzww1RQus7nINSgDfCogZtUXRbeWvAl9/bAKE/PjzKzpdsjwbaNfXswcttyOuW2FoddqeZ1sYSvGyQ3xPfkybrJpwodId6rbVhNRDzOUSebpRqndwjIAN4ilzfmDQ5gAQDWgb4h8mJVcI/grL4Cf1HT/YsLLeGTNIBWS/FZGVdJnPfSWstpXZpNvizBdA7Dhl1NZwj2FbrMJs49vWZcBf1c+x19awKMe0xd5/FMZJ/gZNDKjyec2S4tVREbb18zK0rhDZdxyKG9u3LoAL58DJQReDGI2nDL90g4+WhFLwtHKb8ndrP6/5HiqxdOvL1+uBSrAZb/V6VuXCeltqrGcfbkucCKNGj756NcUAcboNNm7hJfMnQTD3hYE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
