appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: hkl3+un8BzNHl1oUpbfsz+ZQ2D/91ge8B9reGe+33OlpzgXK3wEs+4oqpY8wez9k1lyh4sss4EVa4BR+q5GGFfOI+AO0OVVmGyepfD8EgVcQfobBuysvim84lPaZ+XiXDtDYUecuTX296EOQDwjAG3IEpAyzCE6ZM/XYrx48arxvZ1FhoAPyyILEeqZ4dI3Iyg9DH15YX3J06wuWP5qYa/VAJzVJo8kVHayba0Ob4XnTL47z/WlyE19pm2lycLSIVEUi+bMNeMkVUD7sj9+Qb7bK5G9w4gwYcM8fRIJukfLFNsD03LMBzww1RQus7nINSgDfCogZtUXRbeWvAl9/bAKE/PjzKzpdsjwbaNfXswcttyOuW2FoddqeZ1sYSvGyQ3xPfkybrJpwodId6rbVhNRDzOUSebpRqndwjIAN4ilzfmDQ5gAQDWgb4h8mJVcI/grL4Cf1HT/YsLLeGTNIBWS/FZGVdJnPfSWstpXZpNvizBdA7Dhl1NZwj2FbrMJs49vWZcBf1c+x19awKMe0xd5/FMZJ/gZNDKjyec2S4tVREbb18zK0rhDZdxyKG9u3LoAL58DJQReDGI2nDL90g4+WhFLwtHKb8ndrP6/5HiqxdOvL1+uBSrAZb/V6VuXCeltqrGcfbkucCKNGj756NcUAcboNNm7hJfMnQTD3hYE=}
provider:
  win: azure
conda_forge_output_validation: true
